language: python
python:
  - "2.6"
  - "2.7"
  - "pypy"
  - "3.4"

before_install:
  - if [ $CI_TARGET == "icarus" ]; then
      sudo apt-get update -qq;
      sudo apt-get install -y iverilog;
    fi

install:
  - pip install .

env:
  - CI_TARGET=core
  - CI_TARGET=icarus

matrix:
  allow_failures:
    - python: "3.4"

script: ./ci.sh

notifications:
  email: false
