name: Test myhdl

on: 
  push: 
  pull_request:
  schedule:
    - cron: '0 1 * * 0'
jobs:
  run_lint:
    strategy:
      fail-fast: false # So that one fail doesn't stop remaining tests
    runs-on: ubuntu-latest      
    
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade -r requirements.txt
      - name: Run lint
        continue-on-error: true
        run: |
          pyflakes myhdl
 
  build_iverilog_linux:
    #uses: daxzio/setup-eda/.github/workflows/setup_iverilog.yml@main
    uses: ./.github/workflows/setup_iverilog.yml

  build_code_linux:

    strategy:
      fail-fast: false # So that one fail doesn't stop remaining tests
      matrix:
        python-version: ["3.8", "3.9",  "pypy-3.9", "3.10", "pypy-3.10", "3.11", "3.12"]
        target: [core, iverilog, ghdl]
    runs-on: ubuntu-latest
    needs: [run_lint, build_iverilog_linux]

    env:
      TERM: xterm-256color # for tput in the script file
    
    steps:
      - uses: actions/checkout@v3
      - name: Report Environment
        run: |
          echo "Runing tests with env set to : ${{ matrix.target }}"
      - name: Cache Icarus
        uses: actions/cache@v3
        with:
          path: ${{ needs.build_iverilog_linux.outputs.cache_dir }}
          key: ${{ needs.build_iverilog_linux.outputs.cache_key }}
      - name: Add to PATH
        run: |
          echo "${{ needs.build_iverilog_linux.outputs.cache_dir }}/bin" >> $GITHUB_PATH
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade -r requirements.txt
          python -m pip install .
      - name: Install depenacy for ghdl
        if: matrix.target == 'ghdl'
        uses: ghdl/setup-ghdl@v1
        with:
          version: nightly
          backend: llvm
      - name: Run Tests
        run: |
          make ${{ matrix.target }}
  
  build_code_windows:

    strategy:
      fail-fast: false # So that one fail doesn't stop remaining tests
      matrix:
        python-version: ["3.12"]
        #target: [core, iverilog, ghdl]
        target: [core, ghdl]
    runs-on: windows-latest
    defaults:
      run:
       shell: msys2 {0}
    needs: [run_lint]

    steps:
      - uses: actions/checkout@v4
      - uses: msys2/setup-msys2@v2
        with:
          msystem: ucrt64
          path-type: inherit
          update: true
          pacboy: >-
            make:p
      - name: Report Environment
        run: |
          echo "Runing tests with env set to : ${{ matrix.target }}"
        
      - if: matrix.target == 'ghdl'
        uses: ghdl/setup-ghdl@v1
        with:
          version: nightly
          backend: llvm
          runtime: ucrt64
      - if: matrix.target == 'iverilog'
        name: Choco iverilog
        run: |
          choco install --yes ${{ matrix.target }}
      - if: matrix.target == 'iverilog'
        name: Compile vpi
        run: |
          make iverilog_myhdl.vpi
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
      - name: Set environment variables
        run: |
          echo "C:\\msys64\\mingw64\\bin" >> $GITHUB_PATH          
          echo "${{ env.pythonLocation }}\bin" >> $GITHUB_PATH
          echo "C:\ProgramData\Chocolatey\bin" >> $GITHUB_PATH
      - name: Verify Python installation
        run: python --version
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade -r requirements.txt
          python -m pip install .
      - name: Run Tests
        run: |
          make ${{ matrix.target }}
  
  pypy_release:
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
    runs-on: ubuntu-latest
    needs: [build_code_linux, build_code_windows]
    steps:
      - uses: actions/checkout@v3
      - name: Make PyPi dist release
        run: make dist
      - name: Publish Python distribution to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
